import {describe,it,expect,vi,afterEach} from 'vitest';
import {mkdtemp,writeFile,readFile,stat,symlink,chmod,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';import {join} from 'node:path';import {createHash} from 'node:crypto';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {InMemoryTransport} from '@modelcontextprotocol/sdk/inMemory.js';
import {loadConfig} from '../src/config.js';import {FourthwallClient} from '../src/api/client.js';
import {ALL_TOOLS,validateArguments} from '../src/tools/index.js';import {buildServer} from '../src/server.js';
const directories:string[]=[];
afterEach(async()=>{vi.unstubAllGlobals();await Promise.all(directories.splice(0).map(p=>rm(p,{recursive:true,force:true})));});
async function dir(){const p=await mkdtemp(join(tmpdir(),'fourthwall-fixture-'));directories.push(p);return p;}
const config=()=>loadConfig({FOURTHWALL_USERNAME:'fixture-username',FOURTHWALL_PASSWORD:'fixture-password',FOURTHWALL_MIN_REQUEST_INTERVAL_MS:'0'});
const response=(v:unknown,status=200)=>new Response(v===undefined?null:JSON.stringify(v),{status,headers:{'Content-Type':'application/json'}});
function fixture(replies:Response[]=[]){const calls:{url:URL;init:RequestInit}[]=[];const fetcher=vi.fn(async(u:any,init:any)=>{calls.push({url:new URL(String(u)),init});return replies.shift()??response({id:'fixture-shop'});});const c=new FourthwallClient(config(),fetcher as any,async()=>{});return{c,calls,fetcher};}
async function call(name:string,args:Record<string,any>,c:FourthwallClient){const tool=ALL_TOOLS.find(t=>t.name===name)!;validateArguments(tool,args);return tool.handler(args,c) as Promise<any>;}
async function protocol(c:FourthwallClient,readOnly=false){const server=buildServer({...c.config,readOnly},c);const [a,b]=InMemoryTransport.createLinkedPair();await server.connect(b);const client=new Client({name:'behavior-fixture',version:'1'});await client.connect(a);return{client,close:async()=>{await client.close();await server.close();}};}
const ID='00aa4abd-5778-4199-8161-0b49b2f212e5';
describe('private shop configuration',()=>{
 it('discovers with no credentials',()=>expect(loadConfig({}).accounts).toEqual([]));
 it('never inherits Basic credentials into named empty profiles',async()=>{const c=new FourthwallClient(loadConfig({FOURTHWALL_ACCOUNTS:'[{"name":"isolated"}]',FOURTHWALL_USERNAME:'inherited',FOURTHWALL_PASSWORD:'private-inherited'}));await expect(call('get_shop',{},c)).rejects.toThrow('No valid');});
 it('rejects duplicated profile names',()=>expect(()=>loadConfig({FOURTHWALL_ACCOUNTS:'[{"name":"a"},{"name":"a"}]'})).toThrow('unique'));
 it('rejects mixed Basic/Bearer sources',()=>expect(()=>loadConfig({FOURTHWALL_USERNAME:'u',FOURTHWALL_PASSWORD:'p',FOURTHWALL_ACCESS_TOKEN:'t'})).toThrow('one credential'));
 it('requires a complete Basic pair at request time',async()=>{const c=new FourthwallClient(loadConfig({FOURTHWALL_USERNAME:'fixture-username'}));await expect(call('get_shop',{},c)).rejects.toThrow('No valid');});
 it('sends Basic only to the fixed native API host',async()=>{const f=fixture();await call('get_shop',{},f.c);expect(f.calls[0].url.origin).toBe('https://api.fourthwall.com');expect(f.calls[0].url.pathname).toBe('/open-api/v1.0/shops/current');expect((f.calls[0].init.headers as any).Authorization).toBe('Basic '+Buffer.from('fixture-username:fixture-password').toString('base64'));expect(f.calls[0].init.redirect).toBe('error');});
 it('uses an isolated existing OAuth bearer',async()=>{const fetcher=vi.fn(async()=>response({id:'s'}));const c=new FourthwallClient(loadConfig({FOURTHWALL_ACCOUNTS:JSON.stringify([{name:'shop-a',access_token:'fixture-oauth-a'},{name:'shop-b',access_token:'fixture-oauth-b'}]),FOURTHWALL_MIN_REQUEST_INTERVAL_MS:'0'}),fetcher as any,async()=>{});await call('get_shop',{account:'shop-b'},c);expect((fetcher.mock.calls[0] as any)[1].headers.Authorization).toBe('Bearer fixture-oauth-b');});
 it('keeps profile discovery credential-free',async()=>{const f=fixture();const r=await call('list_accounts',{},f.c);expect(r.accounts[0].authSource).toBe('shop-basic');expect(JSON.stringify(r)).not.toContain('fixture-password');expect(f.calls).toHaveLength(0);});
 it('reads private credential JSON without exposing its content',async()=>{const p=join(await dir(),'credentials.json');await writeFile(p,JSON.stringify({username:'file-user',password:'file-password'}),{mode:0o600});const fetcher=vi.fn(async()=>response({id:'s'}));const c=new FourthwallClient(loadConfig({FOURTHWALL_CREDENTIALS_FILE:p}),fetcher as any,async()=>{});await call('get_shop',{},c);expect(c.redactText('file-user file-password')).toBe('[redacted] [redacted]');});
 it('rejects credential symlinks before fetch',async()=>{const d=await dir();await writeFile(join(d,'real'),'{"access_token":"fixture-file-token"}',{mode:0o600});await symlink(join(d,'real'),join(d,'link'));const f=fixture();const c=new FourthwallClient(loadConfig({FOURTHWALL_CREDENTIALS_FILE:join(d,'link')}),f.fetcher as any);await expect(call('get_shop',{},c)).rejects.toThrow('private credential');expect(f.calls).toHaveLength(0);});
 it('rejects POSIX credential files readable by others',async()=>{if(process.platform==='win32')return;const p=join(await dir(),'public');await writeFile(p,'{"access_token":"fixture-file-token"}');await chmod(p,0o644);const c=new FourthwallClient(loadConfig({FOURTHWALL_CREDENTIALS_FILE:p}));await expect(call('get_shop',{},c)).rejects.toThrow('private credential');});
});
describe('real native request contracts',()=>{
 it('uses zero-based page and size, not legacy cursors',async()=>{const f=fixture();await call('list_products',{page:0,size:25,search:'tee'},f.c);expect(f.calls[0].url.searchParams.get('page')).toBe('0');expect(f.calls[0].url.searchParams.get('size')).toBe('25');await expect(call('list_products',{cursor:'obsolete'},f.c)).rejects.toThrow('additional properties');});
 it('enforces page/size bounds and one-based template pages',async()=>{const f=fixture();await expect(call('list_products',{size:101},f.c)).rejects.toThrow();await expect(call('list_products',{page:-1},f.c)).rejects.toThrow();await expect(call('list_product_templates_paged',{page:0},f.c)).rejects.toThrow();expect(f.calls).toHaveLength(0);});
 it('preserves repeated status arrays and native date filter names',async()=>{const f=fixture();await call('list_orders',{status:['CONFIRMED','SHIPPED'],created_at_gt:'2026-01-01T00:00:00Z'},f.c);expect(f.calls[0].url.searchParams.getAll('status')).toEqual(['CONFIRMED','SHIPPED']);expect(f.calls[0].url.searchParams.get('createdAt[gt]')).toBe('2026-01-01T00:00:00Z');});
 it('rejects inverted native date filters before fetch',async()=>{const f=fixture();await expect(call('list_orders',{created_at_gt:'2026-02-01T00:00:00Z',created_at_lt:'2026-01-01T00:00:00Z'},f.c)).rejects.toThrow('lower bound');expect(f.calls).toHaveLength(0);});
 it('uses native available rather than isAvailable',async()=>{const f=fixture();await call('toggle_product_availability',{product_id:ID,available:false},f.c);expect(JSON.parse(f.calls[0].init.body as string)).toEqual({available:false});await expect(call('toggle_product_availability',{product_id:ID,isAvailable:false},f.c)).rejects.toThrow();});
 it('keeps PUBLIC/HIDDEN lifecycle state separate from availability',async()=>{const f=fixture();await call('update_product_state',{product_id:ID,state:'HIDDEN'},f.c);expect(f.calls[0].url.pathname).toContain('/state');expect(JSON.parse(f.calls[0].init.body as string)).toEqual({state:'HIDDEN'});});
 it('preserves required nested fulfillment items and shippingLabel',async()=>{const f=fixture([response({id:'f'},201)]);const payload={orderId:ID,items:[{variantId:ID,quantity:2}],shippingLabel:{trackingNumber:'fixture-number',trackingCompany:'fixture-carrier'}};await call('create_fulfillment',{payload},f.c);expect(JSON.parse(f.calls[0].init.body as string)).toEqual(payload);});
 it('refuses flat legacy fulfillment bodies',async()=>{const f=fixture();await expect(call('create_fulfillment',{payload:{orderId:ID,orderItemIds:[ID],trackingNumber:'old'}},f.c)).rejects.toThrow('required');expect(f.calls).toHaveLength(0);});
 it('uses native number/productId giveaway body',async()=>{const f=fixture();await call('create_giveaway_links',{number:2,productId:ID},f.c);expect(JSON.parse(f.calls[0].init.body as string)).toEqual({number:2,productId:ID});});
 it('requires both url and allowedTypes when updating webhooks',async()=>{const f=fixture();await expect(call('update_webhook',{webhook_configuration_id:ID,url:'https://example.com/hook'},f.c)).rejects.toThrow('allowedTypes');expect(f.calls).toHaveLength(0);});
 it('serializes typed streaming service objects, rejecting old strings',async()=>{const f=fixture();await expect(call('start_streaming',{services:['twitch']},f.c)).rejects.toThrow();const services=[{type:'TWITCH',broadcasterId:'fixture-broadcaster',broadcasterLogin:'fixture-login'}];await call('start_streaming',{services},f.c);expect(JSON.parse(f.calls[0].init.body as string)).toEqual({services});});
 it('rejects shallow legacy promotion bodies before sending',async()=>{const f=fixture();await expect(call('create_promotion',{payload:{code:'FIXTURE',percentOff:10}},f.c)).rejects.toThrow();expect(f.calls).toHaveLength(0);});
 it('sends the reviewed native shop percentage promotion variant',async()=>{const f=fixture(),payload={type:'SHOP_SINGLE',code:'FIXTURE',discount:{type:'PERCENTAGE',percentage:10,shipping:'Excluded'}};await call('create_promotion',{payload},f.c);expect(JSON.parse(f.calls[0].init.body as string)).toEqual(payload);});
 it('creates hidden digital products with explicit native type',async()=>{const f=fixture([response({productId:ID,images:[]},201)]);await call('create_product',{payload:{type:'digital',name:'Fixture draft',description:'Fixture only',price:9.5}},f.c);expect(JSON.parse(f.calls[0].init.body as string).publishOnCreate).toBe(false);});
 it('rejects unknown product creation type',async()=>{const f=fixture();await expect(call('create_product',{payload:{type:'made-up',name:'Fixture',description:'Fixture',price:5}},f.c)).rejects.toThrow();expect(f.calls).toHaveLength(0);});
 it('accepts a native JSON body file, rejects mixed input',async()=>{const p=join(await dir(),'body.json');await writeFile(p,'{"available":false}');const f=fixture();await call('toggle_product_availability',{product_id:ID,payload_file:p},f.c);await expect(call('toggle_product_availability',{product_id:ID,payload_file:p,available:true},f.c)).rejects.toThrow('mix');});
 it('refuses path traversal and slash-containing IDs',async()=>{const f=fixture();await expect(call('get_product',{product_id:'../other'},f.c)).rejects.toThrow();await expect(call('get_product',{product_id:'..'},f.c)).rejects.toThrow('Unsupported');expect(f.calls).toHaveLength(0);});
});
describe('shared operation policy and API failures',()=>{
 for(const name of ['toggle_product_availability','mark_download_complete','get_public_token','export_resources','upload_file'])it('requires MCP confirmation for '+name,async()=>{const f=fixture(),p=await protocol(f.c);try{const args=name==='get_public_token'?{output_file:join(await dir(),'private.json')}:name==='export_resources'?{operation:'list_products',output_file:join(await dir(),'export.json')}:name==='upload_file'?{receipt_file:'/fixture/receipt',input_file:'/fixture/bytes'}:{product_id:ID,order_id:ID};if(name==='toggle_product_availability')delete args.order_id;if(name==='mark_download_complete')delete args.product_id;const r=await p.client.callTool({name,arguments:args});expect(r.isError).toBe(true);expect(JSON.stringify(r)).toContain('confirm');expect(f.calls).toHaveLength(0);}finally{await p.close();}});
 it('hides effects and refuses direct hidden calls in read-only mode',async()=>{const f=fixture(),p=await protocol(f.c,true);try{expect((await p.client.listTools()).tools).toHaveLength(49);const r=await p.client.callTool({name:'toggle_product_availability',arguments:{product_id:ID,available:false,confirm:true}});expect(r.isError).toBe(true);expect(JSON.stringify(r)).toContain('READ_ONLY');expect(f.calls).toHaveLength(0);}finally{await p.close();}});
 it('treats a documented empty204 archive response as a receipt',async()=>{const f=fixture([response(undefined,204)]);expect(await call('archive_product',{product_id:ID},f.c)).toMatchObject({http_status:204,nativeEmptyReceipt:true});});
 it('refuses missing JSON where a native receipt is required',async()=>{const f=fixture([response(undefined)]);await expect(call('get_shop',{},f.c)).rejects.toThrow('Missing native receipt');});
 it('throws explicit native429 and never retries',async()=>{const f=fixture([response({code:'OPEN_API_TOO_MANY_REQUESTS',status:429},429)]);await expect(call('get_shop',{},f.c)).rejects.toMatchObject({code:'RATE_LIMIT',status:429});expect(f.calls).toHaveLength(1);});
 it('redacts private credentials from native errors',async()=>{const f=fixture([response({detail:'fixture-password',access_token:'fixture-returned-token'},403)]);await expect(call('get_shop',{},f.c)).rejects.toThrow('[redacted]');});
 it('rejects malformed provider responses without retry',async()=>{const f=fixture([new Response('<html>error</html>',{status:200})]);await expect(call('get_shop',{},f.c)).rejects.toThrow('non-JSON');expect(f.calls).toHaveLength(1);});
});
describe('reviewed operational batches',()=>{
 const tasks=[{tool:'toggle_product_availability',arguments:{product_id:ID,available:false}},{tool:'update_product_state',arguments:{product_id:ID,state:'HIDDEN'}}];
 it('previews without network or private credential loading',async()=>{const f=fixture();const r=await call('preview_shop_batch',{tasks},f.c);expect(r.reviewSha256).toMatch(/^[a-f0-9]{64}$/);expect(f.calls).toHaveLength(0);});
 it('binds exact request order before any effects',async()=>{const f=fixture();const r=await call('preview_shop_batch',{tasks},f.c);await expect(call('submit_shop_batch',{tasks:[...tasks].reverse(),review_sha256:r.reviewSha256},f.c)).rejects.toThrow('hash mismatch');expect(f.calls).toHaveLength(0);});
 it('rejects profile and mutable-file overrides in nested batch args',async()=>{const f=fixture();for(const key of ['account','confirm','payload_file','output_file'])await expect(call('preview_shop_batch',{tasks:[{...tasks[0],arguments:{...tasks[0].arguments,[key]:'fixture'}}]},f.c)).rejects.toThrow('Batch cannot');});
 it('prevalidates a late bad task before the first provider request',async()=>{const f=fixture();await expect(call('preview_shop_batch',{tasks:[tasks[0],{tool:'update_webhook',arguments:{webhook_configuration_id:ID,url:'https://example.com/hook'}}]},f.c)).rejects.toThrow();expect(f.calls).toHaveLength(0);});
 it('stops on failure and records known and unattempted work',async()=>{const f=fixture([response({id:ID}),response({code:'FAIL'},500)]);const three=[...tasks,tasks[0]],r=await call('preview_shop_batch',{tasks:three},f.c);try{await call('submit_shop_batch',{tasks:three,review_sha256:r.reviewSha256},f.c);throw Error('unexpected success');}catch(e){const detail=JSON.parse((e as Error).message);expect(detail.knownResults).toHaveLength(1);expect(detail.failedIndex).toBe(1);expect(detail.unattemptedIndices).toEqual([2]);expect(f.calls).toHaveLength(2);}});
});
describe('bounded private exports',()=>{
 const page=(n:number,rows:any[],pages:number)=>({results:rows,page:n,size:2,totalPages:pages});
 it('uses native counters and saves redacted metadata privately',async()=>{const f=fixture([response(page(0,[{id:'a',uploadUrl:'private-url'},{id:'b'}],2)),response(page(1,[{id:'c'}],2))]);const output=join(await dir(),'export.json'),r=await call('export_resources',{operation:'list_products',arguments:{size:2},output_file:output,max_pages:2},f.c);expect(r.items).toBe(3);expect(r.completeWithinRequestedFilters).toBe(true);const saved=JSON.parse(await readFile(output,'utf8'));expect(saved.data[0].uploadUrl).toBe('[redacted]');if(process.platform!=='win32')expect((await stat(output)).mode&0o777).toBe(0o600);});
 it('returns same-page offset continuation when item budget truncates',async()=>{const f=fixture([response(page(0,[{id:'a'},{id:'b'}],2))]);const r=await call('export_resources',{operation:'list_products',arguments:{size:2},max_items:1,output_file:join(await dir(),'part.json')},f.c);expect(r.continuation.arguments.page).toBe(0);expect(r.continuation.start_offset).toBe(1);});
 it('fails closed on inconsistent paging and removes partial output',async()=>{const f=fixture([response(page(99,[{id:'a'}],2))]);const p=join(await dir(),'bad.json');await expect(call('export_resources',{operation:'list_products',arguments:{size:2},output_file:p},f.c)).rejects.toThrow('Invalid native');await expect(stat(p)).rejects.toThrow();});
 it('never overwrites an existing export or submits requests',async()=>{const p=join(await dir(),'existing');await writeFile(p,'keep');const f=fixture();await expect(call('export_resources',{operation:'list_products',output_file:p},f.c)).rejects.toThrow('exclusively');expect(f.calls).toHaveLength(0);expect(await readFile(p,'utf8')).toBe('keep');});
});
describe('private upload receipts and byte transport',()=>{
 const signed={uploadUrl:'https://storage.googleapis.com/fixture-bucket/file?X-Goog-Signature=fixture-signature',fileUrl:'https://storage.googleapis.com/fixture-bucket/file'};
 async function receipt(){const d=await dir(),path=join(d,'receipt.json'),input=join(d,'bytes');await writeFile(input,'abc');await writeFile(path,JSON.stringify({receiptVersion:1,operation:'request_media_upload_url',profile:'default',request:{size:3,contentType:'image/png',fileName:'fixture.png'},...signed}),{mode:0o600});return{path,input};}
 it('saves only private upload metadata and never exposes signed URLs',async()=>{const f=fixture([response(signed,201)]),p=join(await dir(),'receipt.json');const r=await call('request_media_upload_url',{fileName:'fixture.png',contentType:'image/png',size:3,output_file:p},f.c);expect(JSON.stringify(r)).not.toContain('fixture-signature');const saved=JSON.parse(await readFile(p,'utf8'));expect(saved.uploadUrl).toBe(signed.uploadUrl);expect(saved.request.size).toBe(3);});
 it('puts exact bytes with signed headers and no Fourthwall auth',async()=>{const r=await receipt(),fetcher=vi.fn(async()=>new Response(null,{status:200}));vi.stubGlobal('fetch',fetcher);const f=fixture(),out=await call('upload_file',{receipt_file:r.path,input_file:r.input},f.c);expect((fetcher.mock.calls[0] as any)[1].headers).toEqual({'Content-Type':'image/png','x-goog-content-length-range':'0,3'});expect((fetcher.mock.calls[0] as any)[1].redirect).toBe('error');expect(Buffer.from((fetcher.mock.calls[0] as any)[1].body).toString()).toBe('abc');expect(out.sha256).toBe(createHash('sha256').update('abc').digest('hex'));expect(out.publicationPerformed).toBe(false);expect(f.calls).toHaveLength(0);});
 it('rejects input length mismatch before storage upload',async()=>{const r=await receipt();await writeFile(r.input,'different');const fetcher=vi.fn();vi.stubGlobal('fetch',fetcher);await expect(call('upload_file',{receipt_file:r.path,input_file:r.input},fixture().c)).rejects.toThrow('byte length');expect(fetcher).not.toHaveBeenCalled();});
 it('refuses arbitrary targets and profile mismatches',async()=>{const r=await receipt(),fetcher=vi.fn();vi.stubGlobal('fetch',fetcher);const saved=JSON.parse(await readFile(r.path,'utf8'));saved.uploadUrl='https://example.com/private-target';await writeFile(r.path,JSON.stringify(saved));await expect(call('upload_file',{receipt_file:r.path,input_file:r.input},fixture().c)).rejects.toThrow('Google Storage');saved.profile='other-shop';await writeFile(r.path,JSON.stringify(saved));await expect(call('upload_file',{receipt_file:r.path,input_file:r.input},fixture().c)).rejects.toThrow('selected shop');expect(fetcher).not.toHaveBeenCalled();});
 it('rejects expired signed receipts without network',async()=>{const r=await receipt();const saved=JSON.parse(await readFile(r.path,'utf8'));saved.expiresAt='2020-01-01T00:00:00Z';await writeFile(r.path,JSON.stringify(saved));await expect(call('upload_file',{receipt_file:r.path,input_file:r.input},fixture().c)).rejects.toThrow('expired');});
});
